### PR TITLE
Add html.js

### PR DESCRIPTION
**Pull request by virgilt**
Added a new file with HTML questions. Tested in Alexa Developer Console.

### CODE REVIEW

**Review by OcelotDive — CHANGES_REQUESTED** [review]
This is an awesome submission, however when testing periodically the app crashes unexpectedly, I believe this is due to an empty set of curly braces at the end of both GB and US question sets.
Looking at the pull request lines 193, 195, 382 and 384 of the html.js.
If you could remove these and resubmit I would be happy to re-test then approve the pull request.
regards

**Comment by virgilt** [comment]
@OcelotDive I made the changes to the html.js file.

**Comment by OcelotDive** [comment]
Thank you, your contribution passed the certification process and should now be live.

**Comment by virgilt** [comment]
@OcelotDive thank you for merging!

**Pull request merged**
